/*
 * Ansible Automation Platform controller API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Data50 struct {
	// 
	Description string `json:"description,omitempty"`
	// 
	Name string `json:"name"`
	// 
	Organization int32 `json:"organization"`
}
