/*
 * Ansible Automation Platform controller API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Data33 struct {
	// 
	AllowSimultaneous bool `json:"allow_simultaneous,omitempty"`
	// 
	Description string `json:"description,omitempty"`
	// 
	ExtraVars string `json:"extra_vars,omitempty"`
	// Inventory applied as a prompt, assuming job template prompts for inventory
	Inventory int32 `json:"inventory,omitempty"`
	// 
	IsSlicedJob bool `json:"is_sliced_job,omitempty"`
	// If automatically created for a sliced job run, the job template the workflow job was created from.
	JobTemplate string `json:"job_template,omitempty"`
	// 
	Limit string `json:"limit,omitempty"`
	// 
	Name string `json:"name"`
	// 
	ScmBranch string `json:"scm_branch,omitempty"`
	// Personal Access Token for posting back the status to the service API
	WebhookCredential int32 `json:"webhook_credential,omitempty"`
	// Unique identifier of the event that triggered this webhook
	WebhookGuid string `json:"webhook_guid,omitempty"`
	// Service that webhook requests will be accepted from
	WebhookService string `json:"webhook_service,omitempty"`
	// 
	WorkflowJobTemplate string `json:"workflow_job_template,omitempty"`
}
