/*
 * Ansible Automation Platform controller API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Data81 struct {
	// 
	AskLimitOnLaunch bool `json:"ask_limit_on_launch,omitempty"`
	// 
	AskScmBranchOnLaunch bool `json:"ask_scm_branch_on_launch,omitempty"`
	// 
	ExtraVars string `json:"extra_vars,omitempty"`
	// 
	Inventory int32 `json:"inventory,omitempty"`
	// 
	Limit string `json:"limit,omitempty"`
	// 
	ScmBranch string `json:"scm_branch,omitempty"`
}
