/*
 * Ansible Automation Platform controller API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Data11 struct {
	// 
	BecomeEnabled bool `json:"become_enabled,omitempty"`
	// 
	Credential int32 `json:"credential,omitempty"`
	// 
	DiffMode bool `json:"diff_mode,omitempty"`
	// The container image to be used for execution.
	ExecutionEnvironment int32 `json:"execution_environment,omitempty"`
	// 
	ExtraVars string `json:"extra_vars,omitempty"`
	// 
	Forks int32 `json:"forks,omitempty"`
	// 
	Inventory int32 `json:"inventory,omitempty"`
	// 
	JobType string `json:"job_type,omitempty"`
	// 
	Limit string `json:"limit,omitempty"`
	// 
	ModuleArgs string `json:"module_args,omitempty"`
	// 
	ModuleName string `json:"module_name,omitempty"`
	// 
	Verbosity string `json:"verbosity,omitempty"`
}
